apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: development-server
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/dipankardas011/demo-repo.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests/dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: development-server
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./manifests/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: development-server
  targetNamespace: app