apiVersion: v1
kind: Pod
metadata:
  name: blue
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: color
              values:
                - blue
              operator: In
  tolerations:
    - key: color
      value: blue
      operator: Equal
      effect: NoSchedule
  containers:
    - name: pod
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: color
              values:
                - red
              operator: In
  tolerations:
    - key: color
      value: red
      operator: Equal
      effect: NoSchedule
  containers:
    - name: pod
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: green
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: color
              values:
                - green
              operator: In
  tolerations:
    - key: color
      value: green
      operator: Equal
      effect: NoSchedule
  containers:
    - name: pod
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: abcd-color-1
spec:
  
  containers:
    - name: pod
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: abcd-color-2
spec:
  containers:
    - name: pod
      image: nginx:alpine
