---
apiVersion: apps/v1
kind: Deployment
metadata:
 creationTimestamp: null
 labels:
   app: beta-apps
 name: beta-apps
spec:
 replicas: 3
 selector:
   matchLabels:
     app: beta-apps
 template:
   metadata:
     creationTimestamp: null
     labels:
       app: beta-apps
   spec:
     affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: app_type
              values: ["beta"]
              operator: In
     containers:
     - image: nginx
       name: nginx

---

apiVersion: batch/v1
kind: Job
metadata:
 name: whalesay
spec:
 completions: 10
 backoffLimit: 6
 template:
   metadata:
     creationTimestamp: null
   spec:
     containers:
     - command:
       - sh 
       - -c
       - "cowsay I am going to ace CKAD!"
       image: docker/whalesay
       name: whalesay
     restartPolicy: Never
