apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: open-project
spec:
  components:
    - name: server
      type: webservice
      properties:
        image: openproject/community:12
        ports:
          - port: 80
            expose: true
        env:
          - name: OPENPROJECT_SECRET_KEY_BASE
            value: "secret"
          # - name: OPENPROJECT_HOST__NAME
          #   value: "localhost:80"
          - name: OPENPROJECT_HTTPS
            value: "true"
      traits:
        - type: napptive-ingress
          properties:
            port: 80
            path: /
