pipeline {
  agent any
  stages {
    stage ('Build') {
      step {
        echo 'Nice World'
      }
    }
    stage ('Testing') {
      step {
        echo 'Testing .......'
      }
    }
    stage ('Deploy') {
      step {
        echo '☸️ 🐋🐳'
      }
    }
  }
}