apiVersion: v1
kind: Namespace
metadata:
  name: mysql-ns

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    conn: mysql
  namespace: mysql-ns
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: mysql-port
      nodePort: 31001
  selector:
    server: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    pvc: mysql
  namespace: mysql-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
