apiVersion: v1
kind: Namespace
metadata:
  name: mysql-ns

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    conn: mysql
  namespace: mysql-ns
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: mysql-port
      nodePort: 31001
  selector:
    server: mysql
    app.kubernetes.io/name: mysql-pod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    pvc: mysql
  namespace: mysql-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mysql-ingress
#   labels:
#     ingress: mysql
#   namespace: mysql-ns
# spec:
#   rules:
#   - host: mysql-server-local.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: mysql-server
#             port: 
#               number: 3306
# ...
