# sudo docker run -v /var/log/:/logging/log \
    # -e LOG_PATH="/logging/log/pods/*/*/*.log" -e LOKI_URL="http://localhost:3100/loki/api/v1/push" \
    # grafana/fluent-bit-plugin-loki:latest


version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/lib:/var/lib
      - ./config-prom.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  fluentbit:
    image: grafana/fluent-bit-plugin-loki:latest
    environment:
      LOG_PATH: "/var/lib/docker/containers/*/*.log"
      LOKI_URL: "http://loki:3100/loki/api/v1/push"
    networks:
      - loki
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
  fluentd:
    image: grafana/fluent-plugin-loki:master
    command:
      - "fluentd"
      - "-v"
      - "-p"
      - "/fluentd/plugins"
    environment:
      LOKI_URL: http://loki:3100
      LOKI_USERNAME:
      LOKI_PASSWORD:
    deploy:
      mode: global
    configs:
      - source: loki_config
        target: /fluentd/etc/loki/loki.conf
    networks:
      - loki
    volumes:
      - host_logs:/var/log
      # Needed for journald log ingestion:
      - /etc/machine-id:/etc/machine-id
      - /dev/log:/dev/log
      - /var/run/systemd/journal/:/var/run/systemd/journal/
    logging:
      options:
         tag: infra.monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    networks:
      - loki
