apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-workflow
  namespace: default
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
        - port: 8000
          expose: true
      traits:
      - type: napptive-ingress
        properties:
          path: /
          port: 8000
    - name: nginx
      type: webservice
      properties:
        image: nginx:alpine
        ports:
        - port: 80
          expose: true
      traits:
      - type: napptive-ingress
        properties:
          path: /
          port: 80
    - name: pdf-frontend
      type: webservice
      properties:
        image: docker.io/dipugodocker/pdf-editor:1.0-frontend
        ports:
        - port: 80
          expose: true
      traits:
      - type: napptive-ingress
        properties:
          path: /
          port: 80

  workflow:
    steps:
    - name: nginx
      type: apply-component
      properties:
        component: nginx
    - name: express-server
      type: apply-component
      properties:
        component: express-server
    - name: pdf
      type: apply-component
      properties:
        component: pdf-frontend
...
