apiVersion: v1
kind: Pod
metadata:
  name: demo-sec-2
spec:
  containers:
    - image: busybox
      name: secrets-env
      command: ["env"]
      env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: admin
              key: admin-user
        - name: DEV_USER
          valueFrom:
            secretKeyRef:
              name: dev
              key: dev-user
  restartPolicy: Never