apiVersion: v1
kind: Secret
metadata:
  name: demo-sec
data:
  username: ZGlwYW5rYXI=
  password: ZHNkc2Q=
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-secret-use
spec:
  containers:
    - name: demo2
      image: nginx
      volumeMounts:
        - name: dcscdc
          mountPath: "/etc/vol-secret"
  restartPolicy: Never
  volumes:
    - name: dcscdc
      secret:
        secretName: demo-sec