apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-from-cm
data:
  file1: val1
  file2: val2
---

apiVersion: v1
kind: Pod
metadata:
  name: cm-volume
spec:
  containers:
  - name: demo
    image: busybox
    command: ["/bin/sh", "-c", "ls /home/config"]
    volumeMounts:
    - name: cm-volume
      mountPath: "/home/config"
  volumes:
    - name: cm-volume
      configMap:
        name: demo-from-cm
  restartPolicy: Never