apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    run: demo
spec:
  containers:
  - image: busybox
    name: demo
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: HELLO
      valueFrom:
        configMapKeyRef:
          name: demo-my-name
          key: name
  restartPolicy: Never
status: {}