apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-cr
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - secrets
    - services
    verbs:
    - get
    - watch
    - list

  - apiGroups:
    - apps
    resources:
    - deployments
    - services
    verbs:
    - get
    - watch
    - list
