
apiVersion: v1
kind: Pod
metadata:
  name: demo-env
  labels:
    web: pdf-editor

spec:
  containers:
  - name: nice
    image: dipugodocker/pdf-editor:latest
    env:
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: pdf-config
          key: PORT
  restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf-config
data:
  PORT: '5680'

---

apiVersion: v1
kind: Service
metadata:
  name: pdf-editor-sv

spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 5680 # finding how to use environement variables 
  selector:
    web: pdf-editor