apiVersion: v1
kind: Secret
metadata:
  name: mysql-admin-password
type: Opaque
data:
  password: MTIzNAo=
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysqldbms
  serviceName: mysql-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldbms
    spec:
      containers:
      - name: mysqldbms
        image: docker.io/mysql:latest
        volumeMounts:
        - name: www
          mountPath: /var/lib/mysql
        ports:
          - containerPort: 3306
            name: connector
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mysql-admin-password
                key: password
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
# docker run -e MYSQL_ROOT_PASSWORD='1234' -d mysql
# docker ps then docker exec -it <> bash
# mysql -uroot -p
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
spec:
  ports:
  - name: mysql-conn
    port: 3306
    targetPort: connector
    nodePort: 31010
  type: NodePort
  selector:
    app: mysqldbms
...
