---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9377