apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      # tcpSocket:
      #   port: 80
      # httpGet:
      #   path: /
      #   port: 80
      exec:
        command:
          - cat
          - /usr/share/nginx/html/index.html
    ports:
      - containerPort: 80
  restartPolicy: Always
status: {}