# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: node-application
# spec:
#   type: ClusterIP # if dont write then also cluterip
#   ports:
#     - port: 3000
#       targetPort: 80
#       # protocol: TCP
#       # name: web
#   selector:
#     app: nginx-deployment
# ---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  ports:
    - port: 3000  # after exposing this <exposed_ip>:3000
      targetPort: 80
      # protocol: TCP
      # name: web
  selector:
    app: nginx-deployment