apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo
  namespace: volumes
spec:
  containers:
    - image: alpine
      name: empty-dir-container
      command: ['sh', '-c', 'sleep 3000']
      volumeMounts:
        - mountPath: /demo
          name: test-vol
  volumes:
    - name: test-vol
      emptyDir: {}