apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvclaim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
  - name: pv-vol
    persistentVolumeClaim:
      claimName: demo-pvclaim
  containers:
  - name: task-pv-pod
    image: nginx
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: pv-vol
    ports:
      - containerPort: 80
...