apiVersion: v1
kind: Pod
metadata:
  name: pod-using-nfs-demo
spec:
  volumes:
    - name: azure
      persistentVolumeClaim:
        claimName: pvc-azuredisk
  containers:
    - name: app
      image: alpine
      volumeMounts:
      - name: azure
        mountPath: /mnt/azure
      command: ["/bin/sh"]
      args: ["-c", "while true; do cat /proc/meminfo | grep MemFree >> /mnt/memory.txt; sleep 5; done"]
...