apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/<sdfsvsfvfsvdv>/resourceGroups/MC_multiNodeKK2_demo-k8s_swedencentral/providers/Microsoft.Compute/disks/myAKSDisk
    volumeAttributes:
      fsType: ext4
...