/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.web.app;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.InetSocketAddress;
import java.net.URL;
import java.net.URLConnection;
import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should message about its status");
    }
    @Test
    @DisplayName("Home Page testing")
    void TestHeader() throws IOException {
        HttpServer httpServer = HttpServer.create(new InetSocketAddress("localhost", 8001), 0);
        // start the server
        httpServer.createContext("/home", new App.homePage());
        httpServer.start();

        // verify our client code
        URL url = new URL("http://localhost:8001/home");
        URLConnection conn = url.openConnection();
        BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));

        InputStream is = getClass().getClassLoader().getResourceAsStream("index.html");

        assert is != null;
        Scanner fileStream = new Scanner(is);
        StringBuilder fileContents = new StringBuilder();
        while (fileStream.hasNext()){
            fileContents.append(fileStream.nextLine());
        }

        assertEquals(fileContents.toString(), in.readLine());

        // stop the server
        httpServer.stop(2);
    }
}
