apiVersion: v1
kind: Pod
metadata:
  name: cpu-mem-demo2
spec:
  containers:
    - name: cpu-mem-demo2
      image: saiyam911/stress
      resources:
        limits:
          cpu: "3"
          memory: "200Mi"
        requests:
          cpu: "3"
          memory: "100Mi"
      command: ["stress"]
      args: ["--cpu", "3"]