---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-mem-demo1
spec:
  containers:
    - name: cpu-mem-demo1
      image: saiyam911/stress
      resources:
        limits:
          # cpu: "1"
          memory: "200Mi"
        requests:
          # cpu: "500m"
          memory: "100Mi"
      command: ["stress"]
      # args: ["--cpu", "2"]  # used to asking the request to increase the resources
      # args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
      args: ["--vm", "1", "--vm-bytes", "25M", "--vm-hang", "1"]

...