apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 2Gi
