apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-server
  labels:
    app: jenkins
spec:
  containers:
    - name: jenkins-master
      image: docker.io/jenkins/jenkins
      ports:
        - containerPort: 8080
          name: jenkins-port
          protocol: TCP
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: pv-vol
  volumes:
  - name: pv-vol
    persistentVolumeClaim:
      claimName: jenkins-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: jenkins
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: jenkins-port

