---
name: build and push docker image
on:
  push

jobs:
  register:
    name: Package, Publish, and Register
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - name: Get git sha short
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Generate deploy manifest from Jinja template
      uses: cuchi/jinja2-action@v1.1.0
      with:
        template: github-actions/temp/my.j2
        output_file: github-actions/deploy/my.yaml
        strict: true
        variables: |
          image_deploy_tag=sha-${{ steps.vars.outputs.sha_short }}

    - name: Commit deploy manifest on local repo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -s -m "[skip ci] Generate deployment manifests"
        git push

    # - name: Push deploy manifests to local repo
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.AUTO_COMMIT_TOKEN }}
